### ISSUE TITLE
Refactor and complete Bridge code

### ISSUE THREAD

**Issue by Enigmatrix** [Enigmatrix/whidra#21]
Refactor [main.kt](https://github.com/Enigmatrix/whidra/blob/speedy-backend/ghidra/bridge/src/main.kt), split file into the main connection stuff, and the grpc part. Then complete the grpc class given alr, including the other functions

**Comment by Enigmatrix** [comment]
ill be more specific :))

**Comment by cExplr** [comment]
Specific for installation?
